### PR TITLE
fix: watchdog reboot hang, HA stop cleanup, firmware update false positive, SOC cache

### LINKED ISSUE #1171: Camera unresponsive after attempting to reboot
## Describe the bug
When I click "Reboot camera" in the web UI or run `reboot` over ssh or serial, the camera starts the reboot process but never actually resets and comes back up.

## To Reproduce

1. Run `reboot`, or in the webui, click Tools -> Reboot camera
2. Wait
3. See that signs of life have stopped (disconnects from wifi, stops responding over serial)
4. Wait 60 seconds
5. See that the watchdog hasn't triggered a reset
6. See no signs of a fresh boot, like IR filter clicks, serial output, or wifi connection

Disconnecting and reconnecting power allows the camera to boot successfully.

## Expected behavior
Camera finishes shutting down, resets, and comes back up.
Alternatively, the watchdog detects the hang and resets the camera within a minute.
Either way, a successful reboot without needing to disconnect power.

## Logs
<details><summary>UART logs</summary>

```
Going to reboot!

Stopping watchdog ...
- Killing watchdog by PID
stopped watchdog (pid 481)
Stopping LED daemon ...
Stopping watchdog ...
Stopping heartbeat daemon...
Stopping Recording service ...
1138
Checking for upgrade ...
Stopping ONVIF Notify service ...
- Stopping onvif_notify_server by PID from /run/onvif_notify_server.pid
stopped process in pidfile '/run/onvif_notify_server.pid' (pid 2077)
Stopping ONVIF discovery ...
- Stopping wsd_simple_server by PID from /run/wsd_simple_server_wlan0.pid
stopped process in pidfile '/run/wsd_simple_server_wlan0.pid' (pid 2027)
Stopping Recording Storage Manager ...
Stopping rc.local ...
Ciao
Stopping Telegram Bot daemon ...
Stopping HA daemon ...
Stopping mqtt-sub-dispatcher: FAIL
Stopping uhttpd ...
- Killing remaining uhttpd processes
Terminated
Stopping mdnsd ...
- Stopping mdnsd by PID from /run/mdnsd.pid
stopped process in pidfile '/run/mdnsd.pid' (pid 1703)
Stopping crond ...
- Killing crond by PID
stopped crond (pid 1660)
Stopping NTP daemon ...
- Killing ntpd by PID
stopped ntpd (pid 1629)
Unmount /mnt/nfs ...
- /mnt/nfs is not mounted
Stopping WireGuard ...
No WireGuard IP address configured
Stopping network ...
run-parts /etc/network/if-down.d
DHCPv6 disabled on lo
ip addr flush dev lo
ip link set lo down
run-parts /etc/network/if-post-down.d
No bridge ports defined
No VLAN on lo

run-parts /etc/network/if-down.d
- DHCPv6 on wlan0
Stopping odhcp6c on wlan0 ...
- Running service with PID 1469
kill -9 1469
rm -f /run/odhcp6c.pid
ip addr flush dev wlan0 label wlan0
ip link set wlan0 down
run-parts /etc/network/if-post-down.d
No bridge ports defined
No VLAN on wlan0

Stopping WPA Supplicant ...
- Stop wpa_supplicant
Stopping wireless interface ...
ifdown: interface wlan0 not configured
Stopping Prudynt ...
- Killing prudynt by PID
stopped prudynt (pid 1138)
- Killing prudynt by name
stopped prudynt (pid 1138)
- Killing prudynt by full process name /bin/prudynt
no /bin/prudynt found; none killed
```

</details>

## Camera model and hardware, Thingino firmware

Thingino firmware built for tplink_tapo_c110_t23n_sc3336_wq9001
[stable+0400131, 2026-04-06 23:35:10 +0000]

## Additional context
I believe even the first reboot (from the AP-mode config into normal mode) was affected by this problem, but I didn't have serial connected yet. Adding 'debug verbose' to the kernel cmdline didn't seem to produce any additional output during shutdown.

## Diagnostics
https://tb.thingino.com/wb2o

### PR DESCRIPTION
**Pull request by aalaei**
## Summary                                                                                                                                                                                                      
                                                                                                                                                                                                                  
  - **rcK**: Fix device hang on reboot (issue #1171). Was killing the watchdog daemon                                                                                                                             
    with SIGTERM early, which wrote the magic 'V' and disarmed the hardware watchdog —                                                                                                                            
    leaving no recovery path if the kernel reboot stalled. Now kills all services first,
    then SIGKILLs the watchdog (can't write 'V'), then calls `reboot -f`. Hardware                                                                                                                                
    watchdog fires as guaranteed fallback if the kernel path hangs.                                                                                                                                               
                                                                                                                                                                                                                  
  - **thingino-ha S93ha**: `ha-daemon` was missing from the graceful kill list on stop,                                                                                                                           
    and `mosquitto_pub`/`mosquitto_sub` were never cleaned up, leaving orphan processes.                                                                                                                          
                                                                                                                                                                                                                  
  - **thingino-ha ha-state**: When `BUILD_TIME` is absent from `os-release`, `build_date`                                                                                                                         
    was left empty and the firmware up-to-date check was skipped, causing Home Assistant                                                                                                                          
    to show a false firmware upgrade notification even on the latest build. Now falls back                                                                                                                        
    to extracting the date from `COMMIT_ID`.                                                                                                                                                                      
                                                                                                                                                                                                                  
  - **common**: `SOC_FAMILY` and `SOC_MODEL` were forked from `soc(1)` on every script                                                                                                                            
    that sources `/usr/share/common`. Results are now cached in `/run/soc.env` after the                                                                                                                          
    first call.                                                                                                                                                                                                   
                                                                                                                                                                                                                  
  ## Related      
  Fixes https://github.com/themactep/thingino-firmware/issues/1171

### CODE REVIEW

File: overlay/etc/init.d/rcK [hunk 1]
```diff
@@ -1,15 +1,33 @@
 #!/bin/sh
 
-echo -c 196 -e "\n\nGoing to reboot!\n"
+LOG=/overlay/shutdown.log
```
Comment (themactep) [inline overlay/etc/init.d/rcK]: that is a big no. first, we do not write directly to /overlay/, that is handled by overlayfs. second, we do not write logs to the flash chip. all logging happens to tmpfs or to a remote syslog server, if configured.

File: overlay/usr/share/common [hunk 2]
```diff
@@ -18,8 +18,14 @@ PORTAL_MODE_FLAG="/run/portal_mode"
 RESOLV_DEFAULT_FILE="/etc/default/resolv.conf"
 RESOLV_FILE="/etc/resolv.conf"
 RESOLV_WORKING_FILE="/tmp/resolv.conf"
-SOC_FAMILY=$(soc -f)
-SOC_MODEL=$(soc -m)
+_SOC_CACHE="/run/soc.env"
+if [ -f "$_SOC_CACHE" ]; then
```
Comment (themactep) [inline overlay/usr/share/common]: do we really need to cache that? soc requests are cheap and rare, we can afford to query it on demand instead of taking valuable space in overlay.

File: package/thingino-ha/files/S93ha [hunk 3]
```diff
@@ -54,10 +54,11 @@ stop() {
...
 
 	stop_daemon
-	killall -q ha-commands ha-discovery ha-state 2>/dev/null
+	killall -q ha-daemon ha-commands ha-discovery ha-state 2>/dev/null
+	killall -q mosquitto_pub mosquitto_sub 2>/dev/null
 	if ! wait_for_ha_shutdown; then
-		killall -q -9 ha-commands ha-discovery ha-state 2>/dev/null
-		start-stop-daemon -K -s SIGKILL -n ha-daemon 2>/dev/null
+		killall -q -9 ha-daemon ha-commands ha-discovery ha-state 2>/dev/null
+		killall -q -9 mosquitto_pub mosquitto_sub 2>/dev/null
```
Comment (themactep) [inline package/thingino-ha/files/S93ha:61]: we have another process using mqtt subscriptions, the hub agent. we might need to distinguish between those processes collecting pids and killing only those owned by the service.

**Comment by themactep** [comment]
Agent review on behalf of the user:

I found one blocking regression in `package/thingino-ha/files/S93ha`.

`stop()` now terminates `mosquitto_pub` and `mosquitto_sub`, but `wait_for_ha_shutdown()` still relies on `ha_processes_gone()`, and that helper only checks `ha-daemon`, `ha-commands`, `ha-discovery`, and `ha-state`.

That means HA shutdown can report success while a `mosquitto_sub` or `mosquitto_pub` process is still alive. In that case the forced-termination fallback never runs, and the next HA start can still hit the duplicate-client/orphaned-process problem this PR is trying to fix.

Suggested fix: include `mosquitto_pub` and `mosquitto_sub` in `ha_processes_gone()` so the wait path and the termination path cover the same process set.

File: overlay/etc/init.d/rcK (hunk 1 above)
Comment (aalaei) [reply overlay/etc/init.d/rcK]: The flash logging was a mistake, I've dropped it entirely

**Comment by aalaei** [comment]
Thanks for the review! the three points addressed. Please let me know if anything else needs attention!
